//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistriFest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using DataHandling;
    using System.Linq;

    public partial class ADODistriFestEntities : DbContext
    {
        public ADODistriFestEntities()
            : base("name=ADODistriFestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<LoginByUsernamePassword_Result> LoginByUsernamePassword(string _username, string _password)
        {
            var usernameParameter = _username != null ?
                new ObjectParameter("username", _username) :
                new ObjectParameter("username", typeof(string));

            var passwordParameter = "invalid" != null ?
                new ObjectParameter("password", "invalid") :
                new ObjectParameter("password", typeof(string));

            Tuple<string, bool> checktuple = BCryptPasswordHandling.ValidatePassword(_password, _username);

            if (checktuple.Item2)
            {
                passwordParameter = checktuple.Item1 != null ?
                new ObjectParameter("password", checktuple.Item1) :
                new ObjectParameter("password", typeof(string));

            }
            else
            {
                passwordParameter = _password != null ?
                new ObjectParameter("password", _password) :
                new ObjectParameter("password", typeof(string));
            }

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginByUsernamePassword_Result>("LoginByUsernamePassword", usernameParameter, passwordParameter);
        }
    }
}
